language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
env:
  global:
    - BUILD_DIR_NAME=build
    - PUBLISH_DOCS=ON
  matrix:
    - BUILD_MODULE_NAME=VIRGIL_SDK_KEYS
    - BUILD_MODULE_NAME=VIRGIL_EXAMPLES
cache:
  directories:
    - $HOME/cmake
    - $HOME/doxygen
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libcurl4-openssl-dev
      - python-yaml
      - graphviz
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
before_install:
  - bash ./ci/install-cmake.sh
  - bash ./ci/install-credentials.sh
  - bash ./ci/install-doxygen.sh
before_script:
  - bash ./ci/configure.sh
script:
  - bash ./ci/run.sh
after_success:
  - bash ./ci/publish-docs.sh
sudo: false
