sudo: false
language: generic

cache:
  apt: true

matrix:
  include:
    - compiler: gcc
      os: linux
      env: CXX=g++-5 CC=gcc-5 BUILD_DIR_NAME=build PUBLISH_DOCS="NO"
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test
      
    - compiler: clang
      os: linux
      env: CXX=clang++-3.7 CC=clang-3.7 BUILD_DIR_NAME=build PUBLISH_DOCS="YES"
      addons:
        apt:
          packages:
            - clang-3.7
          sources:
              - ubuntu-toolchain-r-test
              - llvm-toolchain-precise-3.7

  exclude:
    - compiler: gcc

cache:
  directories:
    - $HOME/cmake
    - $HOME/doxygen

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - python-yaml
      - graphviz

before_install:
  - bash ./ci/install-cmake.sh
  - bash ./ci/install-doxygen.sh
  - bash ./ci/decrypt-consts.sh
before_script:
  - bash ./ci/configure.sh
script:
  - bash ./ci/run.sh

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local_dir: "docs/html"
  on:
    condition: $PUBLISH_DOCS = "YES"