sudo: false
language: generic

cache:
  apt: true

matrix:
  include:
    - compiler: gcc
      os: linux
      env: CXX=g++-5 CC=gcc-5 BUILD_DIR_NAME=build DOC_BRANCH=master
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test
      
    - compiler: clang
      os: linux
      env: CXX=clang++-3.7 CC=clang-3.7 BUILD_DIR_NAME=build DOC_BRANCH=master
      addons:
        apt:
          packages:
            - clang-3.7
          sources:
              - ubuntu-toolchain-r-test
              - llvm-toolchain-precise-3.7

  exclude:
    - compiler: gcc

cache:
  directories:
    - $HOME/cmake
    - $HOME/doxygen

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - python-yaml
      - graphviz

before_install:
  - bash ./ci/install-cmake.sh
  - bash ./ci/install-doxygen.sh
  - bash ./ci/decrypt-consts.sh
before_script:
  - bash ./ci/configure.sh
script:
  - bash ./ci/run.sh
